# CicleCI Configuration File
version: 2
jobs:
  prebuild:
    docker:
    - image: cypress/base:10
      environment:
      TERM: xterm
    steps:
    - checkout
    - restore_cache:
        keys:
          - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          - v1-deps-{{ .Branch }}
          - v1-deps
    - run:
        name: Installing NPM packages
        command: npm ci
        working_directory: ~/project
    - save_cache:
        key: node-deps-v1-{{ .Branch }}-{{ checksum "~/project/package-lock.json" }}
        paths:
          - ~/.npm
    - run:
        command: npm run linter
        name: Checking formatting styles...
        working_directory: ~/project      
    - run:
        command: npm run start:test & npx wait-on http://localhost:8000/
        name: Starting server for tests
        working_directory: ~/project             
    - run:
        command: npm run cypress:all
        name: Run all cypress tests
        working_directory: ~/project
workflows:
  integration:
    jobs:
    - prebuild
  version: 2