version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          name: Install
          post-steps:
            - run:
                name: Check formatting styles
                command: npm run linter

      - cypress/run:
          name: Electron test
          command: npm run cypress:all
          requires:
            - Install
          start: npm run start:test
          wait-on: 'http://localhost:8000'
          no-workspace: true
